# Generated by Django 5.2.6 on 2025-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securemyassets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('IDENTITY', 'Identity'), ('FINANCIAL', 'Financial'), ('DEVICES', 'Digital Devices'), ('CONTENT', 'Digital Content, Services and Storage'), ('LEGAL', 'Legal'), ('HEALTH', 'Health and Wellness'), ('BUSINESS', 'Business')], max_length=20),
        ),
    ]
